enum ACTION {
	SEND_FILE = "SEND_FILE",
	START_LOADER = "START_LOADER",
	STOP_LOADER = "STOP_LOADER",
	SET_DATA = "SET_DATA",
	SET_ALERT = "SET_ALERT",
	CLEAN_ALERT = "CLEAN_ALERT"
}

export default ACTION;
